package io.goodforgod.http.common.uri;

import java.util.Map;
import java.util.stream.Stream;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * @author Anton Kurako (GoodforGod)
 * @since 16.02.2022
 */
class URITemplateArgumentsPortTests extends Assertions {

    private static Stream<Arguments> source() {
        return Stream.of(
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}", Map.of("v", "value"),
                        "http://example.com:8080/v/value/p"),
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}", Map.of("v", "val100", "m", "value"),
                        "http://example.com:8080/v/val100/p?m=value"),
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}", Map.of("v", "value", "o", "val"),
                        "http://example.com:8080/v/value/p?o=val"),
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}", Map.of("v", "value", "m", "val"),
                        "http://example.com:8080/v/value/p?m=val"),
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}", Map.of("v", "value", "s", "val"),
                        "http://example.com:8080/v/value/p?s=val"),
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}",
                        Map.of("v", "value", "o", "val1", "m", "val2", "s", "val3"),
                        "http://example.com:8080/v/value/p?o=val1&m=val2&s=val3"),
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}", Map.of("v", "value", "m", "val2", "s", "val3"),
                        "http://example.com:8080/v/value/p?m=val2&s=val3"),
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}", Map.of("v", "value", "o", "val1", "s", "val3"),
                        "http://example.com:8080/v/value/p?o=val1&s=val3"),
                Arguments.of("http://example.com:8080/v/{v}/p{?o,m,s}", Map.of("v", "value", "o", "val1", "m", "val2"),
                        "http://example.com:8080/v/value/p?o=val1&m=val2"),
                Arguments.of("http://example.com:8080{+path,x}/here", Map.of("path", "/foo/bar", "x", 1024),
                        "http://example.com:8080/foo/bar,1024/here"),
                Arguments.of("http://example.com:8080/{var}", Map.of("var", "value"), "http://example.com:8080/value"),
                Arguments.of("http://example.com:8080/{var:20}", Map.of("var", "value"), "http://example.com:8080/value"),
                Arguments.of("http://example.com:8080/{var:3}", Map.of("var", "value"), "http://example.com:8080/val"),
                Arguments.of("http://example.com:8080/{semi}", Map.of("semi", ";"), "http://example.com:8080/%3B"),
                Arguments.of("http://example.com:8080/{semi:2}", Map.of("semi", ";"), "http://example.com:8080/%3B"),
                Arguments.of("http://example.com:8080/{hello}", Map.of("hello", "Hello World!"),
                        "http://example.com:8080/Hello%20World%21"),
                Arguments.of("http://example.com:8080/{half}", Map.of("half", "50%"), "http://example.com:8080/50%25"),
                Arguments.of("http://example.com:8080/O{empty}X", Map.of("empty", ""), "http://example.com:8080/OX"),
                Arguments.of("http://example.com:8080/O{undef}X", Map.of("", ""), "http://example.com:8080/OX"),
                Arguments.of("http://example.com:8080/{x,y}", Map.of("x", 1024, "y", 768), "http://example.com:8080/1024,768"),
                Arguments.of("http://example.com:8080/?{x,empty}", Map.of("x", 1024, "empty", ""),
                        "http://example.com:8080/?1024,"),
                Arguments.of("http://example.com:8080/?{x,undef}", Map.of("x", 1024, "empty", ""),
                        "http://example.com:8080/?1024"),
                Arguments.of("http://example.com:8080/?{undef,y}", Map.of("y", 768), "http://example.com:8080/?768"),
                Arguments.of("http://example.com:8080/map?{x,y}", Map.of("x", 1024, "y", 768),
                        "http://example.com:8080/map?1024,768"),
                Arguments.of("http://example.com:8080/{x,hello,y}", Map.of("x", 1024, "y", 768, "hello", "Hello World!"),
                        "http://example.com:8080/1024,Hello%20World%21,768"),
                Arguments.of("http://example.com:8080/{var:30}", Map.of("var", "value"), "http://example.com:8080/value"),
                Arguments.of("http://example.com:8080/{+var}", Map.of("var", "value"), "http://example.com:8080/value"),
                Arguments.of("http://example.com:8080/{+hello}", Map.of("hello", "Hello World!"),
                        "http://example.com:8080/Hello%20World!"),
                Arguments.of("http://example.com:8080/{+half}", Map.of("half", "50%"), "http://example.com:8080/50%25"),
                Arguments.of("http://example.com:8080/{base}index", Map.of("base", "http://example.com/home/"),
                        "http://example.com:8080/http%3A%2F%2Fexample.com%2Fhome%2Findex"),
                Arguments.of("http://example.com:8080/{+base}index", Map.of("base", "http://example.com/home/"),
                        "http://example.com:8080/http://example.com/home/index"),
                Arguments.of("http://example.com:8080/O{+empty}X", Map.of("empty", ""), "http://example.com:8080/OX"),
                Arguments.of("http://example.com:8080/O{+undef}X", Map.of("", ""), "http://example.com:8080/OX"),
                Arguments.of("http://example.com:8080{+path}/here", Map.of("path", "/foo/bar"),
                        "http://example.com:8080/foo/bar/here"),
                Arguments.of("http://example.com:8080/here?ref={+path}", Map.of("path", "/foo/bar"),
                        "http://example.com:8080/here?ref=/foo/bar"),
                Arguments.of("http://example.com:8080/up{+path}{var}/here", Map.of("path", "/foo/bar", "var", "value"),
                        "http://example.com:8080/up/foo/barvalue/here"),
                Arguments.of("http://example.com:8080/{+x,hello,y}", Map.of("x", 1024, "y", 768, "hello", "Hello World!"),
                        "http://example.com:8080/1024,Hello%20World!,768"),
                Arguments.of("http://example.com:8080{+path,x}/here", Map.of("path", "/foo/bar", "x", 1024),
                        "http://example.com:8080/foo/bar,1024/here"),
                Arguments.of("http://example.com:8080{+path:6}/here", Map.of("path", "/foo/bar"),
                        "http://example.com:8080/foo/b/here"),
                Arguments.of("http://example.com:8080/{#var}", Map.of("var", "value"), "http://example.com:8080/#value"),
                Arguments.of("http://example.com:8080/{#hello}", Map.of("hello", "Hello World!"),
                        "http://example.com:8080/#Hello%20World!"),
                Arguments.of("http://example.com:8080/{#half}", Map.of("half", "50%"), "http://example.com:8080/#50%25"),
                Arguments.of("http://example.com:8080/foo{#empty}", Map.of("empty", ""), "http://example.com:8080/foo#"),
                Arguments.of("http://example.com:8080/foo{#undef}", Map.of("", ""), "http://example.com:8080/foo"),
                Arguments.of("http://example.com:8080/X{#var}", Map.of("var", "value"), "http://example.com:8080/X#value"),
                Arguments.of("http://example.com:8080/X{#hello}", Map.of("hello", "Hello World!", "var", "value"),
                        "http://example.com:8080/X#Hello%20World!"),
                Arguments.of("http://example.com:8080/{#x,hello,y}", Map.of("x", 1024, "y", 768, "hello", "Hello World!"),
                        "http://example.com:8080/#1024,Hello%20World!,768"),
                Arguments.of("http://example.com:8080/{#path,x}/here", Map.of("path", "/foo/bar", "x", 1024),
                        "http://example.com:8080/#/foo/bar,1024/here"),
                Arguments.of("http://example.com:8080/{#path:6}/here", Map.of("path", "/foo/bar"),
                        "http://example.com:8080/#/foo/b/here"),
                Arguments.of("http://example.com:8080/X{.var}", Map.of("var", "value"), "http://example.com:8080/X.value"),
                Arguments.of("http://example.com:8080/X{.empty}", Map.of("empty", ""), "http://example.com:8080/X."),
                Arguments.of("http://example.com:8080/X{.undef}", Map.of("", ""), "http://example.com:8080/X"),
                Arguments.of("http://example.com:8080/X{.x,y}", Map.of("x", 1024, "y", 768),
                        "http://example.com:8080/X.1024.768"),
                Arguments.of("http://example.com:8080/{.who}", Map.of("who", "fred"), "http://example.com:8080/.fred"),
                Arguments.of("http://example.com:8080/{.who,who}", Map.of("who", "fred"), "http://example.com:8080/.fred.fred"),
                Arguments.of("http://example.com:8080/{.half,who}", Map.of("half", "50%", "who", "fred"),
                        "http://example.com:8080/.50%25.fred"),
                Arguments.of("http://example.com:8080/X{.var:3}", Map.of("var", "value"), "http://example.com:8080/X.val"),
                Arguments.of("http://example.com:8080{/who}", Map.of("who", "fred"), "http://example.com:8080/fred"),
                Arguments.of("http://example.com:8080{/who,who}", Map.of("who", "fred"), "http://example.com:8080/fred/fred"),
                Arguments.of("http://example.com:8080{/half,who}", Map.of("half", "50%", "who", "fred"),
                        "http://example.com:8080/50%25/fred"),
                Arguments.of("http://example.com:8080{/who,dub}", Map.of("who", "fred", "dub", "me/too"),
                        "http://example.com:8080/fred/me%2Ftoo"),
                Arguments.of("http://example.com:8080{/var}", Map.of("var", "value"), "http://example.com:8080/value"),
                Arguments.of("http://example.com:8080{/var,undef}", Map.of("var", "value"), "http://example.com:8080/value"),
                Arguments.of("http://example.com:8080{/var,empty}", Map.of("var", "value", "empty", ""),
                        "http://example.com:8080/value/"),
                Arguments.of("http://example.com:8080{/var,x}/here", Map.of("var", "value", "x", 1024),
                        "http://example.com:8080/value/1024/here"),
                Arguments.of("http://example.com:8080{/var:1,var}", Map.of("var", "value"), "http://example.com:8080/v/value"),
                Arguments.of("http://example.com:8080/{;who}", Map.of("who", "fred"), "http://example.com:8080/;who=fred"),
                Arguments.of("http://example.com:8080/{;half}", Map.of("half", "50%"), "http://example.com:8080/;half=50%25"),
                Arguments.of("http://example.com:8080/{;empty}", Map.of("empty", ""), "http://example.com:8080/;empty"),
                Arguments.of("http://example.com:8080/{;v,empty,who}", Map.of("v", 6, "empty", "", "who", "fred"),
                        "http://example.com:8080/;v=6;empty;who=fred"),
                Arguments.of("http://example.com:8080/{;v,undef,who}", Map.of("v", 6, "who", "fred"),
                        "http://example.com:8080/;v=6;who=fred"),
                Arguments.of("http://example.com:8080/{;x,y}", Map.of("x", 1024, "y", 768),
                        "http://example.com:8080/;x=1024;y=768"),
                Arguments.of("http://example.com:8080/{;x,y,empty}", Map.of("x", 1024, "y", 768, "empty", ""),
                        "http://example.com:8080/;x=1024;y=768;empty"),
                Arguments.of("http://example.com:8080/{;x,y,undef}", Map.of("x", 1024, "y", 768, "empty", ""),
                        "http://example.com:8080/;x=1024;y=768"),
                Arguments.of("http://example.com:8080/{;hello:5}", Map.of("hello", "Hello World!"),
                        "http://example.com:8080/;hello=Hello"),
                Arguments.of("http://example.com:8080/{?who}", Map.of("who", "fred"), "http://example.com:8080/?who=fred"),
                Arguments.of("http://example.com:8080/{?half}", Map.of("half", "50%"), "http://example.com:8080/?half=50%25"),
                Arguments.of("http://example.com:8080/{?x,y}", Map.of("x", 1024, "y", 768, "empty", ""),
                        "http://example.com:8080/?x=1024&y=768"),
                Arguments.of("http://example.com:8080/{?x,y,empty}", Map.of("x", 1024, "y", 768, "empty", ""),
                        "http://example.com:8080/?x=1024&y=768&empty="),
                Arguments.of("http://example.com:8080/{?x,y,undef}", Map.of("x", 1024, "y", 768, "empty", ""),
                        "http://example.com:8080/?x=1024&y=768"),
                Arguments.of("http://example.com:8080/{?var:3}", Map.of("var", "value"), "http://example.com:8080/?var=val"),
                Arguments.of("http://example.com:8080/?fixed=yes{&x}", Map.of("x", 1024),
                        "http://example.com:8080/?fixed=yes&x=1024"),
                Arguments.of("http://example.com:8080/{&x,y,empty}", Map.of("x", 1024, "y", 768, "empty", ""),
                        "http://example.com:8080/&x=1024&y=768&empty="),
                Arguments.of("http://example.com:8080/{&var:3}", Map.of("var", "value"), "http://example.com:8080/&var=val"));
    }

    @ParameterizedTest
    @MethodSource("source")
    void testQueryParamMethodForUri(String template, Map<String, Object> params, String expected) {
        final URITemplate uriTemplate = new URITemplate(template);
        assertEquals(expected, uriTemplate.expand(params));
    }
}
